FileManagementSystem/FileManagementSystem/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('manageFiles.urls')),
    path('File/',include('manageFiles.urls'), name='File'),
    path('admin/', admin.site.urls),
]

FileManagementSystem/manageFiles/urls.py
from inspect import formatargspec
from django.urls import path
from . import views

urlpatterns = [
    path('',views.create_file,name='create_file'),
    path('List/', views.File_list, name='File.List'),
    path('ajax/load-departments/', views.load_departments, name='ajax_load_departments'),
    path('ajax/load-sections/', views.load_sections, name='ajax_load_sections'),
    path('pdf<int:id>/', views.GeneratePdf, name='File_pdf_print'),
]

FileManagementSystem/manageFiles/models.py
from asyncio.windows_events import NULL
from django.db import models
from . import dropdownChoices

# Create your models here.

class JGDivision(models.Model):
    DivisionName = models.CharField(max_length=200, blank=True, null=True)
    NothiCode = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return self.DivisionName or ' '


class JGDepartment(models.Model):
    DepartmentName = models.CharField(max_length=200, blank=True, null=True)
    JGDivision = models.ForeignKey(
        JGDivision, blank=True, null=True, on_delete=models.CASCADE)
    NothiCode = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return self.DepartmentName or ' '


class JGSection(models.Model):
    SectionName = models.CharField(max_length=200, blank=True, null=True)
    JGDepartment = models.ForeignKey(
        JGDepartment, blank=True, null=True, on_delete=models.CASCADE)
    NothiCode = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return self.SectionName or ' '


class JGSubSection(models.Model):
    SubSectionName = models.CharField(max_length=200, blank=True, null=True)
    JGSection = models.ForeignKey(
        JGSection, blank=True, null=True, on_delete=models.CASCADE)
    NothiCode = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return self.SubSectionName or ' '


class File(models.Model):
    file_name = models.CharField(max_length=200, blank=True, null=True)
    file_number = models.CharField(max_length=200, blank=True, null=True)
    file_type = models.CharField(max_length=200, blank=True, null=True)
    file_class = models.CharField(max_length=10, blank=True, null=True, choices=dropdownChoices.ChoicesFileClass)
    file_section = models.ForeignKey(
        JGSection, blank=True, null=True, on_delete=models.CASCADE)
    FileCreationDate = models.DateTimeField(auto_now_add=False, auto_now=False)

    def __str__(self):
        return self.file_name or ' '

FileManagementSystem/manageFiles/forms.py
from django import forms
from .models import File, JGDepartment, JGDivision, JGSection

class FileForm(forms.ModelForm):
    class Meta:

        model = File
        fields = '__all__'

        widgets = {
                'FileCreationDate': forms.TextInput(attrs={'type': 'date'})

        }
        labels = {
            'file_name': 'নথির বিষয়',
            'file_number': 'নথির নম্বর',
            'file_type': 'নথির ধরণ',
            'file_class': 'নথির শ্রেণি',
            'file_section': 'নথির শাখা',
            'FileCreationDate' : 'নথি তৈরির তারিখ',
        }
    

    def __init__(self, *args, **kwargs):
        super(FileForm, self).__init__(*args, **kwargs)
        
        self.fields['file_type'].empty_label = "নথির ধরণ নির্বাচন করুন"
        self.fields['file_class'].empty_label = "নথির শ্রেণি নির্বাচন করুন"

        # if 'file_division' in self.data:
        #     try:
        #         file_division_id = int(self.data.get('file_division'))
        #         self.fields['file_department'].queryset = JGDepartment.objects.filter(JGDivision_id=file_division_id).order_by('NothiCode')
        #     except (ValueError, TypeError):
        #         pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['file_department'].queryset = self.instance.file_division.file_department_set.order_by('NothiCode')

        
        # self.fields["file_section"].queryset = JGSection.objects.none()
        # if 'file_department' in self.data:
        #     try:
        #         file_department_id = int(self.data.get('file_department'))
        #         self.fields['file_section'].queryset = JGSection.objects.filter(JGDepartment_id=file_department_id).order_by('NothiCode')
        #     except (ValueError, TypeError):
        #         pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['file_section'].queryset = self.instance.file_department.file_section_set.order_by('NothiCode')

FileManagementSystem/manageFiles/views.py
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.utils.formats import get_format
from distutils import filelist
from django.shortcuts import redirect, render
import bangla
from .import JG_functions


from manageFiles.models import JGDepartment, JGDivision, JGSection,File
from .forms import FileForm
from django.http import HttpResponseBadRequest
from django.http import HttpResponse
from django.views.generic import View
from weasyprint import HTML
from manageFiles import models
# from .processPDF import html_to_pdf
from django.template.loader import render_to_string

#Delete
from django.http import HttpResponseRedirect
from django.urls import reverse
import tempfile

# def GeneratePdf(request, id):
#     data = models.File.objects.get(pk=id)
#     open('templates/temp.html', "w" , encoding="UTF-8").write(render_to_string('result.html', {'data': data}))

#     # Converting the HTML template into a PDF file
#     pdf = html_to_pdf('temp.html')
    
#     # rendering the template
#     return HttpResponse(pdf, content_type='application/pdf')
def GeneratePdf(request, id):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; attachment; filename=newfile' + \
        str(datetime.now())+'.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    Z = File.objects.get(pk=id)
    data={ 'data': Z }
    d=int(str(DateFormat(Z.FileCreationDate).format('d')))
    m=int(str(DateFormat(Z.FileCreationDate).format('m')))
    y=int(str(DateFormat(Z.FileCreationDate).format('Y')))

    dBN = bangla.convert_english_digit_to_bangla_digit(str(DateFormat(Z.FileCreationDate).format('d')))
    mBN = JG_functions.BanglaMonthSort(int(DateFormat(Z.FileCreationDate).format('m')))
    yBN = bangla.convert_english_digit_to_bangla_digit(str(DateFormat(Z.FileCreationDate).format('Y')))
    F_Bdate = dBN + ' ' + mBN+ ', ' + yBN

    data = data|{'F_Date':bangla.get_date(d,m,y)}
    data = data|{'F_Bdate':F_Bdate}
    html_string = render_to_string(
         'result.html',{'data':data})

    html = HTML(string=html_string,base_url=request.build_absolute_uri())
 
    resultfile = html.write_pdf()

    with tempfile.NamedTemporaryFile(delete=True)as output:
        output.write(resultfile)
        output.flush()
        output.seek(0)
        response.write(output.read())

    return response
    

def FileList_delete(request, id):
    id = File.objects.get(pk=id)
    id.delete()
    return HttpResponseRedirect(reverse('create_file'))
   
 
def create_file(request):

    form = FileForm()

    if request.method == 'POST':
        form = FileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/File/List')
    context = {'form':form}
    return render(request, 'X/form_add_new_file.html', context)
   

def new_func(request):
    return render(request, 'index.html')


def load_departments(request):
    division_id = request.GET.get('file_division')
    departments = JGDepartment.objects.filter(JGDivision_id=division_id).order_by('NothiCode')
    return render(request, 'X/departments_dropdown_list_options.html', {'departments': departments})

def load_sections(request):
    department_id = request.GET.get('file_department')
    sections = JGSection.objects.filter(JGDepartment=department_id).order_by('NothiCode')
    return render(request, 'X/sections_dropdown_list_options.html', {'sections': sections})


def File_list(request):
    data = File.objects.all()
    lst_data = {'Dt':data}
    return render(request,'file_list.html',lst_data)

FileManagementSystem/templates/X/departments_dropdown_list_options.html
<option value="">---------</option>
{% for department in departments %}
<option value="{{ department.pk }}">{{ department.DepartmentName}}</option>
{% endfor %}

FileManagementSystem/templates/X/form_add_new_file.html
{% extends "common.html" %} 
{% load crispy_forms_tags %}
{% block contents %} 

 <h3>Add New File</h3>
<hr>

<div class="jumbotron align-center">
  <form action="" id="fileForm" style="background-color:#e2e5e8" autocomplete="off" method="post" >
    {% csrf_token %}
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-2">{{ form.file_type|as_crispy_field }}</div>
      <div class="col-md-2">{{ form.file_class|as_crispy_field }}</div>
      <div class="col-md-3">{{ form.file_section|as_crispy_field }}</div>
      <div class="col-md-2">{{ form.FileCreationDate|as_crispy_field }}</div>
      <div class="col-md-2"></div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-9">{{ form.file_name|as_crispy_field}}</div>
      <div class="col-md-2"></div>
    </div>
    
    <br>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-9">{{ form.file_number|as_crispy_field}}</div>
        <div class="col-md-2"></div>
      </div>
      <br>
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-3">
        <button  type='submit' class="btn btn-success btn-lg">
          {{header_ico_tag.ico|safe}}
          &nbsp;<b>ADD</b></button>
      </div>
    </div>
    
  </form>
</div>

<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_file_division").change(function () {
      var url = $("#fileForm").attr("data-departments-url");  // get the url of the `load_departments` view
      var divisionId = $(this).val();  // get the selected division ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-departments/)
        data: {
          'file_division': divisionId       // add the division id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_departments` view function
          $("#id_file_department").html(data);  // replace the contents of the department input with the data that came from the server
        }
      });

    });
	
	$("#id_file_department").change(function () {
      var url = $("#fileForm").attr("data-sections-url");  
      var departmentID = $(this).val();  

      $.ajax({                       
        url: '{% url 'ajax_load_sections' %}',                    
        data: {
          'file_department': departmentID       
        },
        success: function (data) {   
          $("#id_file_section").html(data);  
        }
      });

    });
  </script> -->
  

{% endblock contents %}

FileManagementSystem/templates/X/sections_dropdown_list_options.html
<option value="">---------</option>
{% for sec in sections %}
<option value="{{ sec.pk }}">{{ sec.SectionName}}</option>
{% endfor %}

FileManagementSystem/templates/common.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<div class="container">
  {% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-warning"> {% endcomment %}
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">  </span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active"  href="{% url 'create_file' %}"><i class="fas fa-home text text-success"></i>&nbsp;নতুন নথি তৈরি</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'File.List' %}"><i class="fas fa-list-alt text-success"></i>&nbsp; নথিসমূহ</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>
  <br><br>

    {% block contents %}
    {% endblock contents %}
  <!-- JavaScript Bundle with Popper -->
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  
</body>
</html>

FileManagementSystem/templates/file_list.html
{% extends "common.html" %}

{% block contents %}

<div class="table-responsive">
    <table class="table align-middle table-striped table-dark">
      <thead class="table-dark align-middle">
        <th scope="col" class="text-center">#</th>
        <th scope="col">নথির বিষয়</th>
        <th scope="col">নথির নম্বর</th>
        <th scope="col">নথির ধরণ</th>
        <th scope="col">নথির শ্রেণি</th>
        <th scope="col">নথির শাখা</th>
        <th scope="col">তারিখ</th>
        <th scope="col">অপশন</th>
        
      </thead>
      <tbody>
      {% for row in Dt %}
          <tr>
          <th class="table-dark text-center">{{ forloop.counter }}</th>
          <td>{{row.file_name}}</td>
          <td>{{row.file_number}}</td>
          <td>{{row.file_type}}</td>
          <td>{{row.file_class}}</td>
          <td>{{row.file_section}}</td>
          <td>{{row.FileCreationDate}}</td>
          <!-- for delete -->
            <td class="text-center">      
              <form action="{% url 'File_pdf_print' row.id %}" method="get">
                {% csrf_token %}
      
              <button type="submit" class="btn btn btn-primary text-center" data-bs-toggle="tooltip" data-bs-placement="top" title="Print">
               Print
              </button>
              </form> 
            </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
  </div>

{% endblock contents %}

FileManagementSystem/templates/index.html
{% extends "common.html" %} 

{% block contents %} 
<h1>This is home page. Add new file operation will be done in this page.</h1>
{% endblock contents %} 

FileManagementSystem/templates/result.html
<!DOCTYPE html>
  {% load static %}

<html lang="en">
<head>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>‌জালালাবাদ গ্যাস টি এ্যান্ড ডি সিস্টেম লিঃ</title>
      <style>
      html * {
        font-size: 17px;
        line-height: 1.625;
        color: #2020131;
        font-family: Nikosh;
      }
    </style>
</head>

<body>


  <br> <br> <br> <br><br><br>

<div class="container">
  <div class="row">
    
    <div class="col-2 text-center"><span class= 'border border-end border-dark'><img src="{% static 'media/JG_1.png' %}" alt=""><br>
      <h6 class="border border-dark">নথি শ্রেণি<br>"{{ data.data.file_class }}"</h6>
    </div>

    <div class="col-1 text-center"><p>বিষয়ঃ</p></div>
    <div class="col-8"><p>{{ data.data.file_name }}</p>
    
  <table style="width:100%">
  <tr>
    <th rowspan="2">নথি নং-{{ data.data.file_number }}, &nbsp &nbsp &nbsp তারিখঃ</th>
    <td style='border-bottom: 1pt solid black; text-align:center;'>{{ data.F_Bdate }}</td>
  </tr>
  <tr>
    <td  style='text-align:center;'>{{ data.F_Date.date }} {{ data.F_Date.month }}, {{ data.F_Date.year }}</td>
  </tr>
  </table>
          <!-- <hr> -->
        {% comment %} <script>var My_Dt="নথি নং-{{ data.file_number }}, {{ data.FileCreationDate|date:'M d, Y' }}";</script> {% endcomment %}
        <h6 class="text-end">[{{ data.data.file_section }}]</h6>
    </div>
    </div>
</div>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
 
</html>